//----------------------------------------------------------------------
// VERSION Linux M4i/M4x/M2p Kernel Driver
//----------------------------------------------------------------------

#ifndef LX_M4KDRV_VERSION_H
#define LX_M4KDRV_VERSION_H



/*
**************************************************************************

Kernel version

Do not change the version.h file manually as it's autoamtic generated by
a script file from verison.template. Only change the file version.template

**************************************************************************
*/

#define SPCM4_KRNLVER_VERSION     3              // main version
#define SPCM4_KRNLVER_SUBVERSION 12 // subversion
#define SPCM4_KRNLVER_BUILD       23358        // build version



/*
**************************************************************************
Conversion routines for define to string
**************************************************************************
*/

#define SPCM4_KRNLDRIVER_VERSION ((SPCM4_KRNLVER_VERSION << 24) | (SPCM4_KRNLVER_SUBVERSION <<16) | SPCM4_KRNLVER_BUILD)

// macro to kernvert define to string
#define TO_STRING( z) #z

// force preprocessor to first replace the constant and to then convert to string
#define LX_REPLACE_FIRST(Wert) TO_STRING(Wert)

// set up the string in the form 4.05 build 999
#if (SPCM4_KRNLVER_SUBVERSION<10)
#	define RSC_STR_SPCM4_KDRV_VERSION LX_REPLACE_FIRST(SPCM4_KRNLVER_VERSION) ".0" LX_REPLACE_FIRST(SPCM4_KRNLVER_SUBVERSION) " build " LX_REPLACE_FIRST(SPCM4_KRNLVER_BUILD)
#else
#	define RSC_STR_SPCM4_KDRV_VERSION LX_REPLACE_FIRST(SPCM4_KRNLVER_VERSION) "." LX_REPLACE_FIRST(SPCM4_KRNLVER_SUBVERSION) " build " LX_REPLACE_FIRST(SPCM4_KRNLVER_BUILD)
#endif


#endif // __M4KDRV_VERSION
