/*
**************************************************************************

spcm_version.h                                 (c) Spectrum GmbH , 10/2005

**************************************************************************

Do not change the version file manually as it's automatic generated by
a script file from template file. Only change the file spcm_version.template

**************************************************************************
*/


/*
**************************************************************************
DLL
**************************************************************************
*/

#define SPCM_DLLVER_VERSION     7           // main version
#define SPCM_DLLVER_SUBVERSION 7 // subversion
#define SPCM_DLLVER_BUILD       23371     // build version
#define SPCM_DLLVER_PRIVATE	    0           // private version

#define SPCM_DLLDRV_VERSION      ((SPCM_DLLVER_VERSION << 24) | (SPCM_DLLVER_SUBVERSION <<16) | SPCM_DLLVER_BUILD)
#define SPCM_DLLDRV_RVERSION       SPCM_DLLVER_VERSION,SPCM_DLLVER_SUBVERSION,SPCM_DLLVER_BUILD,SPCM_DLLVER_PRIVATE


/*
**************************************************************************
Conversion to string
**************************************************************************
*/
#define TO_STRING( z) #z
#define REPLACE_FIRST(Value) TO_STRING(Value)
#if (SPCM_DLLVER_SUBVERSION<10)
#	define SPCM_DLLDRV_STRVERSION REPLACE_FIRST(SPCM_DLLVER_VERSION) ".0" REPLACE_FIRST(SPCM_DLLVER_SUBVERSION) "." REPLACE_FIRST(SPCM_DLLVER_BUILD)
#else
#	define SPCM_DLLDRV_STRVERSION REPLACE_FIRST(SPCM_DLLVER_VERSION) "." REPLACE_FIRST(SPCM_DLLVER_SUBVERSION) "." REPLACE_FIRST(SPCM_DLLVER_BUILD)
#endif
// ***********************************************************************

