PACKAGE_NAME=spcm4
PACKAGE_VERSION=3.12.23358

DEST_MODULE_LOCATION=/extra
BUILT_MODULE_NAME=spcm4
BUILT_MODULE_LOCATION=m4i_krnl_linux/

MAKE="'make' -C m4i_krnl_linux/ "
CLEAN="'make' -C m4i_krnl_linux/ clean"
AUTOINSTALL="yes"
